version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: NodeTest
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

  api:
    image: node:14.17.3
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node src/index.js
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"