version: "3"

services: 
    node:
        container_name: node
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo: 
        container_name: mongoDatabase
        image: mongo
        ports:
            - "21017:21017"